language: python

sudo: required
dist: precise

install:
  - sudo apt-get install -y
      wget
      python-dev
      python-pip
      cmake
      g++
  - pip install psutil

script:
  - sudo dmidecode
  - python start.py
