language: python

sudo: required
dist: trusty

install:
  - sudo apt-get install -y
      wget
      python-dev
      python-pip
      cmake
      g++
  - pip install psutil
  - sudo pip install psutil

script:
  - python -c 'print "Hello"'
  - python -c 'import platform; print platform.platform()'
  - python -c 'import psutil; print psutil.virtual_memory()'
  - python start.py
